parameters:
#    lebed_user.example.class: Lebed\UserBundle\Example

services:
#    lebed_user.example:
#        class: %lebed_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
