lebed_guestbook_homepage:
    pattern:  /{_locale}
    defaults: { _controller: LebedGuestbookBundle:Default:index, _locale: 'ru' }
    requirements:
        _locale: en|ru
lebed_guestbook_about:
    pattern: /about
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'LebedGuestbookBundle:Static:about.html.twig'
        maxAge:       86400
        sharedMaxAge: 86400
lebed_guestbook_viewPost:
    pattern: /post/{slug}
    defaults: {_controller: LebedGuestbookBundle:Default:show }
lebed_guestbook_viewMessages:
    pattern: /viewMessages
    defaults: { _controller: LebedGuestbookBundle:Message:viewMessages }
lebed_guestbook_search:
    pattern: /search
    defaults: { _controller: LebedGuestbookBundle:Searcher:search}
lebed_guestbook_viewPostsOfCategory:
    pattern: /category/{id}
    defaults: { _controller: LebedGuestbookBundle:Default:viewPostsOfCategory}