lebed_guestbook:
    resource: "@LebedGuestbookBundle/Resources/config/routing.yml"
    prefix:   /
lebed_fos_user:
    resource: "@LebedUserBundle/Resources/config/routing.yml"
    prefix: /
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect