lebed_guestbook:
    resource: "@LebedGuestbookBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path:     /login
    defaults: { _controller: LebedGuestbookBundle:Security:login }
login_check:
    path: /login_check
