<?php

namespace Lebed\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findCountPostsByIdCategory($id)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT COUNT(p.id) FROM LebedGuestbookBundle:Post p WHERE p.category = $id")
            ->getResult();
    }

    public function findLatestPostsLimit($limit)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM LebedGuestbookBundle:Post p ORDER BY p.id DESC')
            ->setMaxResults($limit)
            ->getResult();
    }
}
